# Generated by Django 3.2.6 on 2021-08-27 02:48

import Course.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Teacher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=200)),
                ('Description', models.TextField()),
                ('PreRequisites', models.CharField(max_length=200)),
                ('References', models.CharField(max_length=1000)),
                ('StateCourse', models.CharField(choices=[('Active', 'Active'), ('Pause', 'Pause'), ('Completed', 'Completed')], max_length=20)),
                ('DateTimeSubmit', models.DateTimeField(auto_now_add=True)),
                ('LastTimeUpdated', models.DateTimeField(blank=True, null=True)),
                ('Image', models.ImageField(null=True, upload_to=Course.models.UploadTo_ImageCourse)),
                ('Price', models.CharField(max_length=15)),
                ('Teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Teacher.teacher')),
            ],
        ),
        migrations.CreateModel(
            name='SectionCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(max_length=150)),
                ('DateTimeSubmit', models.DateTimeField(auto_now_add=True)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.course')),
            ],
        ),
        migrations.CreateModel(
            name='VisitCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTimeSubmit', models.DateTimeField(auto_now_add=True)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.course')),
            ],
        ),
        migrations.CreateModel(
            name='VideoCourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Video', models.FileField(null=True, upload_to=Course.models.UploadTo_VideoCourse)),
                ('DurationVideo', models.CharField(blank=True, max_length=20, null=True)),
                ('DateTimeSubmit', models.DateTimeField(auto_now_add=True)),
                ('StateVideo', models.CharField(choices=[('200', '200'), ('400', '400')], default='400', max_length=30)),
                ('Section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.sectioncourse')),
            ],
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=200, null=True)),
                ('Percent', models.CharField(max_length=5)),
                ('Time', models.CharField(max_length=15)),
                ('DateTimeSubmit', models.DateTimeField(auto_now_add=True)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.course')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Text', models.TextField()),
                ('TextAnswer', models.TextField(blank=True, default=None, null=True)),
                ('DateTimeSubmit', models.DateTimeField(auto_now_add=True)),
                ('DateTimeSubmitAnswer', models.DateTimeField(blank=True, null=True)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.course')),
            ],
        ),
    ]
