# Generated by Django 3.2.6 on 2021-08-27 02:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FirstName', models.CharField(blank=True, max_length=200, null=True)),
                ('LastName', models.CharField(blank=True, max_length=200, null=True)),
                ('Email', models.CharField(max_length=70)),
                ('PhoneNumber', models.CharField(blank=True, max_length=20, null=True)),
                ('City', models.CharField(blank=True, max_length=30, null=True)),
                ('DateTimeJoin', models.DateTimeField(auto_now_add=True)),
                ('UserName', models.CharField(max_length=100)),
                ('Password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DateTimeSubmit', models.DateTimeField(auto_now_add=True)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.course')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.student')),
            ],
        ),
        migrations.CreateModel(
            name='CoursePurchased',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('HasDiscount', models.BooleanField(default=False)),
                ('TitleDiscount', models.CharField(blank=True, max_length=200, null=True)),
                ('PercentDiscount', models.CharField(blank=True, max_length=5, null=True)),
                ('PriceWithOutDiscount', models.CharField(blank=True, max_length=200, null=True)),
                ('Price', models.CharField(blank=True, max_length=200, null=True)),
                ('DateTimeSubmit', models.DateTimeField(auto_now_add=True)),
                ('Course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Course.course')),
                ('Student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Student.student')),
            ],
        ),
    ]
